version: '3.9'

services:
    sql-db:
        container_name: SQL-Server
        image: mcr.microsoft.com/mssql/server:2019-latest

        ports:
            - 1433:1433
        
        environment:
          SA_PASSWORD: "Pwd1234!"
          ACCEPT_EULA: "Y"